-- Review manifest: hunks grouped into an ordered list of reading steps.
-- Generated by Claude Code (headless), cached per PR + head SHA.
local M = {}

---@class prtour.Step
---@field title string
---@field note string|nil
---@field hunks integer[]

local INSTRUCTIONS = [[
You are preparing a guided code-review tour of a pull request.
stdin contains the PR's diff hunks, each introduced by a line '### hunk <id> - <file>:<line>'.
You are running inside the repo with the PR branch checked out; read surrounding files if that helps you understand the structure.

Order the hunks the way a reviewer should read them: foundations first (types, schemas, data model), then core logic, then call sites and UI, with tests next to the code they test. Group related hunks into narrative steps that each tell one part of the story. Put mechanical churn (imports, renames, lockfiles, generated files, formatting) into a final step titled "Mechanical changes" that the reviewer can skim.

Reply with ONLY a JSON object, no prose, no code fences:
{"steps":[{"title":"short step title","note":"one sentence: what to check here","hunks":[<ids>]}]}
Every hunk id must appear exactly once across all steps.
]]

local function cache_path(key, sha)
  local dir = vim.fn.stdpath 'cache' .. '/prtour'
  vim.fn.mkdir(dir, 'p')
  return ('%s/manifest-%s-%s.json'):format(dir, key, sha)
end

---@param hunks prtour.Hunk[]
---@return string
local function hunks_text(hunks)
  local parts = {}
  for _, h in ipairs(hunks) do
    parts[#parts + 1] = ('### hunk %d - %s:%d%s'):format(h.id, h.file, h.start_line, h.deleted and ' (file deleted)' or '')
    local n = math.min(#h.lines, 25)
    for i = 1, n do
      parts[#parts + 1] = h.lines[i]
    end
    if #h.lines > n then
      parts[#parts + 1] = ('(... %d more lines)'):format(#h.lines - n)
    end
  end
  return table.concat(parts, '\n')
end

--- One step per file, diff order. Used when Claude is unavailable.
---@param hunks prtour.Hunk[]
---@return prtour.Step[]
local function fallback_steps(hunks)
  local steps, by_file = {}, {}
  for _, h in ipairs(hunks) do
    if not by_file[h.file] then
      by_file[h.file] = { title = h.file, hunks = {} }
      steps[#steps + 1] = by_file[h.file]
    end
    table.insert(by_file[h.file].hunks, h.id)
  end
  return steps
end

--- Normalize Claude's answer: drop unknown/duplicate ids, append missing ones.
---@param steps prtour.Step[]
---@param hunks prtour.Hunk[]
---@return prtour.Step[]|nil
local function validate(steps, hunks)
  if type(steps) ~= 'table' or #steps == 0 then
    return nil
  end
  local known, seen = {}, {}
  for _, h in ipairs(hunks) do
    known[h.id] = true
  end
  local out = {}
  for _, step in ipairs(steps) do
    if type(step) == 'table' and type(step.title) == 'string' and type(step.hunks) == 'table' then
      local ids = {}
      for _, id in ipairs(step.hunks) do
        if known[id] and not seen[id] then
          seen[id] = true
          ids[#ids + 1] = id
        end
      end
      if #ids > 0 then
        out[#out + 1] = { title = step.title, note = step.note, hunks = ids }
      end
    end
  end
  local missing = {}
  for _, h in ipairs(hunks) do
    if not seen[h.id] then
      missing[#missing + 1] = h.id
    end
  end
  if #missing > 0 then
    out[#out + 1] = { title = 'Not covered by the tour plan', hunks = missing }
  end
  return #out > 0 and out or nil
end

---@param opts {key: string|integer, sha: string, hunks: prtour.Hunk[], claude_cmd: string[]}
---@param p prtour.Progress
---@param cb fun(steps: prtour.Step[], from_cache: boolean|nil)
function M.get(opts, p, cb)
  local path = cache_path(tostring(opts.key or opts.pr), opts.sha)
  local f = io.open(path, 'r')
  if f then
    local ok, cached = pcall(vim.json.decode, f:read '*a')
    f:close()
    local steps = ok and validate(cached, opts.hunks) or nil
    if steps then
      return cb(steps, true)
    end
  end
  p:report 'asking Claude for a reading order (can take a minute)'
  local cmd = vim.deepcopy(opts.claude_cmd or { 'claude', '-p' })
  cmd[#cmd + 1] = INSTRUCTIONS
  local model = (require('prtour').config.models or {}).manifest
  if model then
    cmd[#cmd + 1] = '--model=' .. model
  end
  vim.system(cmd, { text = true, stdin = hunks_text(opts.hunks) }, function(out)
    vim.schedule(function()
      local steps
      if out.code == 0 then
        local json = (out.stdout or ''):match '(%b{})'
        local ok, decoded = pcall(vim.json.decode, json or '')
        steps = ok and validate(decoded and decoded.steps, opts.hunks) or nil
      end
      if steps then
        local wf = io.open(path, 'w')
        if wf then
          wf:write(vim.json.encode(steps))
          wf:close()
        end
      else
        vim.notify('prtour: Claude ordering failed, falling back to file order', vim.log.levels.WARN)
        steps = fallback_steps(opts.hunks)
      end
      cb(steps)
    end)
  end)
end

return M
